[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.128.0"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[context.branch-deploy]
  command = "hugo --buildDrafts --buildFuture"

[context.next.environment]
  HUGO_VERSION = "0.128.0"


[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
